### ISSUE TITLE
Please take a look at the https://github.com/psygames/UnityWebSocket - they have options for the socket connections

### ISSUE THREAD

**Issue by studentutu** [Iblis/UniTaskWebSocket#2]
Please take a look into the https://github.com/psygames/UnityWebSocket
They had a few issues with tls connections

**Comment by Iblis** [comment]
Hi there, I had a look at the repo, but could not identify what you are referring to. Could you give me a hint at what explicitly I should have a look at? 
I am not aware of any issues with secure transport. You can also check the example repo at https://github.com/Iblis/UniTaskWebSocketExample or even run the WebGL example at https://iblis.github.io/UniTaskWebSocketExample/. This example connects to an echo Webservice via wss / secure connection. 
One thing that I could find in the commit history of psygames UnityWebSocktes was setting up an ssl cert, but it looks like this is for a local webserver?

**Comment by studentutu** [comment]
yep, sorry for that.
Could you add support for the sub protocols?
There are custom protocols that you can add to the websocket so that it can use http2 connections

**Comment by Iblis** [comment]
Got it. Thanks for the clarification! I 'stumbled' over that already when porting the WebSockets to UniTask. I am trying to add it soon.

**Comment by Iblis** [comment]
I just put it in, hope it is what you've expected. You should be able to test it by updating to v0.3.0
